(ns cuisine-sorting-hat.core
  (:gen-class)
  (:require [clojure.set]
            [ring.adapter.jetty :as jetty]))

(def countries
  "Should be a full list of countries."
  #{"Afghanistan"
    "Albania"
    "Algeria"
    "Andorra"
    "Angola"
    "Antigua and Barbuda"
    "Argentina"
    "Armenia"
    "Australia"
    "Austria"
    "Azerbaijan"
    "Bahamas"
    "Bahrain"
    "Bangladesh"
    "Barbados"
    "Belarus"
    "Belgium"
    "Belize"
    "Benin"
    "Bhutan"
    "Bolivia"
    "Bosnia and Herzegovina"
    "Botswana"
    "Brazil"
    "Brunei"
    "Bulgaria"
    "Burkina Faso"
    "Burundi"
    "Cabo Verde"
    "Cambodia"
    "Cameroon"
    "Canada"
    "Central African Republic (CAR)"
    "Chad"
    "Chile"
    "China"
    "Colombia"
    "Comoros"
    "Congo, Democratic Republic of the"
    "Congo, Republic of the"
    "Costa Rica"
    "Cote d'Ivoire"
    "Croatia"
    "Cuba"
    "Cyprus"
    "Czechia"
    "Denmark"
    "Djibouti"
    "Dominica"
    "Dominican Republic"
    "Ecuador"
    "Egypt"
    "El Salvador"
    "Equatorial Guinea"
    "Eritrea"
    "Estonia"
    "Eswatini (formerly Swaziland)"
    "Ethiopia"
    "Fiji"
    "Finland"
    "France"
    "Gabon"
    "Gambia"
    "Georgia"
    "Germany"
    "Ghana"
    "Greece"
    "Grenada"
    "Guatemala"
    "Guinea"
    "Guinea-Bissau"
    "Guyana"
    "Haiti"
    "Honduras"
    "Hungary"
    "Iceland"
    "India"
    "Indonesia"
    "Iran"
    "Iraq"
    "Ireland"
    "Israel"
    "Italy"
    "Jamaica"
    "Japan"
    "Jordan"
    "Kazakhstan"
    "Kenya"
    "Kiribati"
    "Kosovo"
    "Kuwait"
    "Kyrgyzstan"
    "Laos"
    "Latvia"
    "Lebanon"
    "Lesotho"
    "Liberia"
    "Libya"
    "Liechtenstein"
    "Lithuania"
    "Luxembourg"
    "Madagascar"
    "Malawi"
    "Malaysia"
    "Maldives"
    "Mali"
    "Malta"
    "Marshall Islands"
    "Mauritania"
    "Mauritius"
    "Mexico"
    "Micronesia"
    "Moldova"
    "Monaco"
    "Mongolia"
    "Montenegro"
    "Morocco"
    "Mozambique"
    "Myanmar (formerly Burma)"
    "Namibia"
    "Nauru"
    "Nepal"
    "Netherlands"
    "New Zealand"
    "Nicaragua"
    "Niger"
    "Nigeria"
    "North Korea"
    "North Macedonia (formerly Macedonia)"
    "Norway"
    "Oman"
    "Pakistan"
    "Palau"
    "Palestine"
    "Panama"
    "Papua New Guinea"
    "Paraguay"
    "Peru"
    "Philippines"
    "Poland"
    "Portugal"
    "Qatar"
    "Romania"
    "Russia"
    "Rwanda"
    "Saint Kitts and Nevis"
    "Saint Lucia"
    "Saint Vincent and the Grenadines"
    "Samoa"
    "San Marino"
    "Sao Tome and Principe"
    "Saudi Arabia"
    "Senegal"
    "Serbia"
    "Seychelles"
    "Sierra Leone"
    "Singapore"
    "Slovakia"
    "Slovenia"
    "Solomon Islands"
    "Somalia"
    "South Africa"
    "South Korea"
    "South Sudan"
    "Spain"
    "Sri Lanka"
    "Sudan"
    "Suriname"
    "Sweden"
    "Switzerland"
    "Syria"
    "Taiwan"
    "Tajikistan"
    "Tanzania"
    "Thailand"
    "Timor-Leste"
    "Togo"
    "Tonga"
    "Trinidad and Tobago"
    "Tunisia"
    "Turkey"
    "Turkmenistan"
    "Tuvalu"
    "Uganda"
    "Ukraine"
    "United Arab Emirates (UAE)"
    "United Kingdom (UK)"
    "United States of America (USA)"
    "Uruguay"
    "Uzbekistan"
    "Vanuatu"
    "Vatican City (Holy See)"
    "Venezuela"
    "Vietnam"
    "Yemen"
    "Zambia"
    "Zimbabwe"})

(def excluded-countries
  "List of countries to exclude. Most probably cuisine is not represented in SF"
  #{"Vanuatu"
    "Benin"
    "Djibouti"
    "Bahamas"})

(defn rand-country
  "return random country from countries except exclusions"
  ([countries]
   (rand-nth countries))
  ([countries exclusions]
   (rand-nth (into [] (clojure.set/difference countries exclusions)))))

(defn response []
  (str "Please, try the famous cuisine of "
       (rand-country countries excluded-countries)
       " today!"))

(defn handler [request]
  {:status 200
   :headers {"Content-Type" "text/html"}
   :body (response)})

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (jetty/run-jetty handler {:port 8080}))
