name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: eastwood
      run: lein eastwood
    - name: kibit
      run: lein kibit
    - name: cljfmt
      run: lein cljfmt check
    - name: bikeshed
      run: lein bikeshed
